spring:
  profiles:
    active:
    - dev
  data:
    mongodb:
      uri: mongodb+srv://dou:xdll241xd@cluster0.kb07l.mongodb.net/Cluster0?retryWrites=true&w=majority

management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
      mongo:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,metrics